server:
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://db/flyway
    username: root
    password: root
    maxActive: 1
    maxIdle: 1
    minIdle: 1
    initialSize: 1
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
    validationQuery: SELECT 1

flyway:
    target: 3
